---
swagger: '2.0'
info:
  version: 1.0.0
  title: EFA API
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: localhost:8000
consumes:
  - application/json
produces:
  - application/json
paths:
  /participants:
    get:
      summary: Retrieves every participant
      responses:
        200:
          description: 'Fetches a list of participants'
    post:
      parameters:
        - in: body
          name: participant
          required: true
          schema:
            $ref: '#/definitions/ParticipantRegistration'
      responses:
        '201':
          description: 'Add a new participant'
  '/participants/{id}':
    get:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: 'Fetch a participant by ID'
          schema:
            $ref: '#/definitions/Participant'
    delete:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '204':
          description: 'Delete a participant by ID'

definitions:
  ParticipantRegistration:
    type: object
    properties:
      firstname: { type: string }
      lastname: { type: string }

  Participant:
    type: object
    properties:
      firstname: { type: string }
      lastname: { type: string }
      personalid: { type: string }
      participations: {
        type: array,
        items: { type: object }
      }
      outputindicators: { type: object }
